from app.graph.state import ReceptionistState

EMERGENCY_MESSAGE = (
    "This sounds like it could be a medical emergency. Please hang up and call "
    "911 right away, or go to your nearest emergency room."
)

GENERAL_ESCALATION_MESSAGE = (
    "Let me connect you with a member of our staff who can help with that."
)


def escalation_node(state: ReceptionistState) -> dict:
    """
    Handles all escalation paths:
    1. is_emergency == True -> hard-coded safety message, never generated by
       an LLM, so it can't be softened, hedged, or delayed under latency.
    2. Low-confidence or "unclear" classification -> hand off to staff rather
       than guess at an FAQ answer.
    3. Any other non-FAQ routing -> general handoff message.
    """
    if state.get("is_emergency"):
        message = EMERGENCY_MESSAGE
    else:
        message = GENERAL_ESCALATION_MESSAGE

    return {
        "response_text": message,
        "escalated": True,
        "transcript": state.get("transcript", []) + [{"role": "assistant", "content": message}],
    }